package Daje::Plugin::Database::SqlLite;
use Mojo::Base -signatures;

use DBI;

has 'dbh' ;
has 'data_dir';
has 'path';

sub get_dbh($self) {
    unless (defined $dbh) {
        $self->_open_database();
    }
    return $dbh;
}

sub _open_database($self) {
    my $new = $self->_datadir();
    $self->_open();
    $self->_add_table();
}

sub _add_table($self){
    my $script = $self->_table_script();
    my $sth = $dbh->prepare($script) or die "Couldn't create table: " . $dbh->errstr;;
    $sth->execute() or die "Couldn't create table: " . $dbh->errstr;;;
}

sub _open($self){
    my $dbfile = $data_dir .'/generate.db';
    $dbh = DBI->connect("dbi:SQLite:dbname=$dbfile","","",
        {
            PrintError => 1, AutoCommit => 1
        }
    ) or die $DBI::errstr;
}

sub _datadir($self) {
    my $new = 0;
    try {
        $data_dir = $path->dirname . "/data";
        if (!(-d $data_dir)) {
            mkdir("$data_dir", 0700);
            $new = 1;
        }
    } catch ($e) {
        die "Failed creating datadir '$e";
    };

    return $new
}

sub _table_script($self) {
    return qq{
            CREATE TABLE IF NOT EXISTS file_hashes (
                file text PRIMARY KEY,
                hash text NOT NULL,
                moddatetime text
            );
        };
}


1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Plugin::Database::SqlLite


=head1 REQUIRES

L<DBI> 

L<Mojo::Base> 


=head1 METHODS

=head2 get_dbh($self)

 get_dbh($self)();


=cut

